"""esquema inicial

Revision ID: 0c0fd1b97d2f
Revises: 
Create Date: 2026-08-17 00:04:45.891710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, usadas pelo Alembic.
revision: str = '0c0fd1b97d2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('audio_dir', sa.Text(), nullable=False),
    sa.Column('audio_state', sa.Text(), server_default='original', nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("audio_state IN ('original', 'compressed', 'removed')", name='ck_meetings_audio_state'),
    sa.CheckConstraint("source IN ('capture', 'import')", name='ck_meetings_source'),
    sa.CheckConstraint("status IN ('recorded', 'transcribing', 'transcribed', 'summarized', 'transcription_failed', 'summary_failed')", name='ck_meetings_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('meetings_queue_idx', 'meetings', ['status', 'started_at'], unique=False)
    op.create_index('meetings_started_idx', 'meetings', [sa.literal_column('started_at DESC')], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('summaries_meeting_idx', 'summaries', ['meeting_id', sa.literal_column('generated_at DESC')], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('speaker', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('channels', sa.SmallInteger(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('device', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'speaker', name='uq_tracks_meeting_speaker')
    )
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.Column('speaker', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', text)", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('segments_meeting_idx', 'segments', ['meeting_id', 'start_ms'], unique=False)
    op.create_index('segments_search_idx', 'segments', ['search'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('segments_search_idx', table_name='segments', postgresql_using='gin')
    op.drop_index('segments_meeting_idx', table_name='segments')
    op.drop_table('segments')
    op.drop_table('tracks')
    op.drop_index('summaries_meeting_idx', table_name='summaries')
    op.drop_table('summaries')
    op.drop_index('meetings_started_idx', table_name='meetings')
    op.drop_index('meetings_queue_idx', table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
